### ISSUE TITLE
Fix Sample Type/Class swap for Roslin branch

### ISSUE THREAD

**Issue by ckandoth** [mskcc/pipeline-kickoff#101]
To be compliant with [cbioportal format](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#clinical-sample-columns), **SAMPLE_TYPE** in data_clinical.txt files must describe the TNM classification (Primary, Metastasis, Recurrence, etc.) and **SAMPLE_CLASS** must describe the specimen type (Resection, Biopsy, Blood, CellLine, Organoid, etc.). This odd naming is originally due to cBioPortal inheriting [TCGA terminology](https://gdc.cancer.gov/resources-tcga-users/tcga-code-tables/sample-type-codes) for "Sample Type".

This is the correct mapping between LIMS and cBioPortal field names:
SpecimenType -> SAMPLE_CLASS
CMOSampleClass -> SAMPLE_TYPE

These LIMS fields and their picklist of valid values cannot be changed. The sample-intake UI (rex) also calls these fields "Specimen Type" (SAMPLE_CLASS per cBioPortal) and "Sample Class" (SAMPLE_TYPE per cBioPortal), but thankfully, the picklist keeps the values consistent.

[pipeline-kickoff](https://github.com/mskcc/pipeline-kickoff) assigns the values to the wrong columns in data_clinical.txt. It looks like the BIC pipeline consumes these swapped columns and swaps them again in their pipeline before upload to cBioPortal. But for Roslin, we would prefer to have this fixed in pipeline-kickoff itself, to keep Roslin portable. Be careful not to fix this in the BIC branch.

**Comment by ckandoth** [comment]
Related fix for new codebase - https://github.com/mskcc/roslin-internal-services/issues/6

**Comment by imprezka88** [comment]
This change should be only done in data_clinical file or in whole code I should treat those values in an opposite way? I can just display those values swapped or keep those values swapped but in this case it can change some other logic as well using it.

**Comment by imprezka88** [comment]
This is the result you would like to have? http://plvpipetrack1.mskcc.org:8090/secure/attachment/62653/Proj_08236_sample_data_clinical.txt

**Comment by imprezka88** [comment]
those values are also put in manifest file. I know roslin doesn’t use it but if in the future someone will be using it should those values be swapped there as well?

**Comment by ckandoth** [comment]
@imprezka88 thanks for checking. Let us leave all current logic unchanged. You can do the swap of values only for data_clinical file in Roslin branch. And we can close this ticket.

**Comment by imprezka88** [comment]
Just for future reference: "Class" and "Sample_type" columns will remain unchanged. Current state is that Class column contains SAMPLE_CLASS and Sample_type contains SPECIMEN_PRESERVATION_TYPE.

Change for this issue contains change in data_clinical file ONLY

**Comment by imprezka88** [comment]
PR https://github.com/mskcc/pipeline-kickoff/pull/105
