### ISSUE TITLE
Review/revise logic that creates new RSL issues

### ISSUE THREAD

**Issue by ckandoth** [mskcc/pipeline-kickoff#103]
Review and document current logic that triggers creation of RSL issues, and discuss with @soccin and @ckandoth on whether/how it should change. There will now be many IMPACT/HemePACT projects marked as "No PM", but these will now be managed by an IGO PM and CAS team.

**Comment by imprezka88** [comment]
@soccin @ckandoth here is documentation of current behaviour for opening jira tickets: http://plvpipetrack1.mskcc.org:8099/display/IDT/Opening+new+jira+tickets+for+requests
let me know if you'd like to change anything in this logic or something is not clear

**Comment by ckandoth** [comment]
@timosong and @Zuojian-Tang please review this logic with Ewa. Then talk to Marisa/Cassidy/Pavitra on how the logic should be revised. Let @soccin have final sign-off before deployment. Thanks.

**Comment by imprezka88** [comment]
opened issue in piops https://github.com/mskcc/piops/issues/142 as changes are made in that codebase
