### ISSUE TITLE
Smart pairing must locate normals from other requests in project

### ISSUE THREAD

**Issue by ckandoth** [mskcc/pipeline-kickoff#104]
A request may include tumors where the normal was sequenced in a previous request (e.g. 07078_F has some tumors with matched normals in 07078_B), or the normal is expected to be sequenced in a new request (e.g. 08106_C has tumors with normals coming later in 08106_D). In the latter situation, the CAS team will put the Roslin run on "Hold" until the new request containing matched normals has been sequenced, and then we will trigger input re-generation.

During input generation and re-generation, find matched normals in the same request as usual. If not found, then find matched normals (of same assay) in other requests of the same project. If still not found, then use a pooled normal. If pooled normal is not available, then set normal to "na".

In the case of "na" normals, do not produce error. CAS team is responsible for locating a "closest related normal" downstream of pipeline-kickoff, and overriding Roslin inputs manually. We will automate this later.

**Comment by imprezka88** [comment]
Should the logic with finding normals in other requests be same as smart pairing within a request?
The logic is:
1. find sequencer-compatible normals
2. out of them find specimen preservation type-compatible normals
3. out of them find tissue site-compatible normals

**Comment by imprezka88** [comment]
if request is eg 05667_CJ should I also look for in 05667? Should I rely on child-parent relationship between project and request or request names?

**Comment by imprezka88** [comment]
@ckandoth  do those normal samples need to have passed qc? should they have the same restrictions as any other samples which are processed?

**Comment by ckandoth** [comment]
- Requirements 2 and 3 for smart-pairing seem unnecessary. But leave them unchanged, until I learn more.
- Use parent-child relationship of Project and Request records to find all other requests in a project.
- The normals you choose must be `Passed` or `IGO Complete` in the `SeqAnalysisSampleQC` record. Use `PostSeqAnalysisQC` only if it exist and says `Failed`.

**Comment by imprezka88** [comment]
From Cyriac:
the additional normals from other requests should be added to pairing, grouping, mapping files. No need to add to sample_patient. And data_clinical does not have information on normals anyway.
