### ISSUE TITLE
Fix logic for PI and investigator names/emails

### ISSUE THREAD

**Issue by ckandoth** [mskcc/pipeline-kickoff#106]
```bash
Request file errors:
-Invalid email(mskcc) for PI_E-mail (value found: NA).; Invalid email(mskcc) for Investigator_E-mail (value found: NA).
```
This error is very common, and is happening because of incorrect logic. If information manually entered by PMs is missing/invalid, then use the information that investigators populated via iLabs which should never be empty, though it could be invalid. See http://plvpipetrack1.mskcc.org:8099/display/PipelineInitiation/Request+file for correct logic.

**Comment by imprezka88** [comment]
@ckandoth should there be distinction between CMO/non-CMO project as it is now (https://github.com/mskcc/pipeline-kickoff/blob/master/src/main/java/org/mskcc/kickoff/printer/RequestFilePrinter.java#L175)
 or logic should be always like on confluence page?

**Comment by ckandoth** [comment]
@imprezka88 the distinction between CMO and non-CMO project is no longer necessary, and is also now inaccurate because policy has changed on assigned PM. Instead, use the logic as [defined here](http://plvpipetrack1.mskcc.org:8099/display/PipelineInitiation/Request+file).
