### ISSUE TITLE
Add extra contact info in request.txt

### ISSUE THREAD

**Issue by ckandoth** [mskcc/pipeline-kickoff#107]
Extract content of field `MailTo` in `Request` records into a new line in the `request.txt` file named `MailTo`. For example, `MailTo` in `09459_F` contains 4 email addresses of people we would not otherwise have emailed. FYI @timosong

**Comment by imprezka88** [comment]
@ckandoth what value should be there for sample set? concatenated MailTo from all requests? MailTi for Prime request or something else?

**Comment by ckandoth** [comment]
For sample-sets, use only information from the prime request. Thanks!
