### ISSUE TITLE
Use ProjectName from request record, not project

### ISSUE THREAD

**Issue by ckandoth** [mskcc/pipeline-kickoff#109]
There are 6 sample-sets starting with `set_09459*` that got incorrectly associated with `ProjectName: AK-ptmpimp` in the request.txt instead of `NS-ptmpimp`. Prefer the latter which comes from the Request record. If that is undefined in the Request record, then use the value from the parent Project record.

**Comment by imprezka88** [comment]
@ckandoth project name should be used from which request? From prime one?

**Comment by imprezka88** [comment]
@ckandoth is it only for sample sets or should work the same for single request? The logic in code is that it’s taken from parent project
those fields are taken from project https://github.com/mskcc/pipeline-kickoff/blob/master/src/main/java/org/mskcc/kickoff/lims/ProjectInfoRetriever.java#L136
just CMO_PROJECT_ID (ProjectName) should be taken from request instead or all above?

**Comment by ckandoth** [comment]
@imprezka88 this applies to all requests and sample-sets. Always prefer the CMO_PROJECT_ID (ProjectName) from request instead of what the parent project records say.
