### ISSUE TITLE
Retain original COLLAB_ID in data_clinical, and add IGO_ID

### ISSUE THREAD

**Issue by ckandoth** [mskcc/pipeline-kickoff#110]
Sometimes the `COLLAB_ID` in data_clinical has an `s_` prefix added by pipeline-kickoff code or all `-` symbols are replaced with `_`. This makes it difficult for the investigator to locate their sample. Please ensure that the original value remains unchanged.

The IGO sample ID is also useful for debugging how the sample traveled through IGO extraction, library prep, sequencing, and qc workflows. Add `IGO_ID` as an extra column.

These two features are not a priority, but they would be very nice to have.

**Comment by imprezka88** [comment]
I don't see s_ being concatenated, it is for first column SAMPLE_ID. Have you also seen it added in COLLAB_ID column? Do you care which column number will IGO_ID be?

**Comment by ckandoth** [comment]
Feng likely already removed the `s_`, but `-` is still being replaced with `_` for sure. That needs to stop for COLLAB_ID. SAMPLE_ID still needs to have `s_` - don't make any changes to its logic. IGO_ID can be any column but not the first one.

**Comment by ckandoth** [comment]
@imprezka88 this is low priority to implement, but still needed. An example is 09413_D, where COLLAB_IDs like `SFS-PDX4-P3` are being changed to `SFS_PDX4_P3` in the data_clinical.txt file. Can you disable that '-' replacement for COLLAB_ID? And add IGO_ID as an extra column.

**Comment by imprezka88** [comment]
@ckandoth I actually implemented that but never opened PR for it :/ just opened one #134
