### ISSUE TITLE
Assay mismatch between tumors and normals

### ISSUE THREAD

**Issue by ckandoth** [mskcc/pipeline-kickoff#133]
As requested in https://github.com/mskcc/pipeline-kickoff/issues/104, the retrieved normals must belong to the same assay as the tumors. For example, in 09413_D and 04763_AD, WES normals are being retrieved for use with IMPACT tumors. The assay must exactly match between tumor and normal e.g. IMPACT468 tumors vs IMPACT468 normals.

**Comment by imprezka88** [comment]
#135
